// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "config.proto" (package "ruthless.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ruthless.v1.Config
 */
export interface Config {
    /**
     * @generated from protobuf field: ruthless.v1.Config.Limits limits = 1
     */
    limits?: Config_Limits;
}
/**
 * @generated from protobuf message ruthless.v1.Config.Limits
 */
export interface Config_Limits {
    /**
     * @generated from protobuf field: uint32 card_text_limit = 1
     */
    cardTextLimit: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Config$Type extends MessageType<Config> {
    constructor() {
        super("ruthless.v1.Config", [
            { no: 1, name: "limits", kind: "message", T: () => Config_Limits }
        ]);
    }
    create(value?: PartialMessage<Config>): Config {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Config>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Config): Config {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ruthless.v1.Config.Limits limits */ 1:
                    message.limits = Config_Limits.internalBinaryRead(reader, reader.uint32(), options, message.limits);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Config, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ruthless.v1.Config.Limits limits = 1; */
        if (message.limits)
            Config_Limits.internalBinaryWrite(message.limits, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ruthless.v1.Config
 */
export const Config = new Config$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Config_Limits$Type extends MessageType<Config_Limits> {
    constructor() {
        super("ruthless.v1.Config.Limits", [
            { no: 1, name: "card_text_limit", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<Config_Limits>): Config_Limits {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cardTextLimit = 0;
        if (value !== undefined)
            reflectionMergePartial<Config_Limits>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Config_Limits): Config_Limits {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 card_text_limit */ 1:
                    message.cardTextLimit = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Config_Limits, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 card_text_limit = 1; */
        if (message.cardTextLimit !== 0)
            writer.tag(1, WireType.Varint).uint32(message.cardTextLimit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ruthless.v1.Config.Limits
 */
export const Config_Limits = new Config_Limits$Type();
