// @generated by protobuf-ts 2.11.1 with parameter long_type_string,client_generic
// @generated from protobuf file "api/v1/config.proto" (package "ruthless.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ruthless.v1.Config
 */
export interface Config {
    /**
     * @generated from protobuf field: ruthless.v1.ConfigPublic public = 1
     */
    public?: ConfigPublic;
    /**
     * @generated from protobuf field: ruthless.v1.ConfigPrivate private = 2
     */
    private?: ConfigPrivate;
}
/**
 * @generated from protobuf message ruthless.v1.ConfigPublic
 */
export interface ConfigPublic {
    /**
     * @generated from protobuf field: ruthless.v1.ConfigPublic.Limits limits = 1
     */
    limits?: ConfigPublic_Limits;
    /**
     * @generated from protobuf field: ruthless.v1.ConfigPublic.Game game = 2
     */
    game?: ConfigPublic_Game;
    /**
     * @generated from protobuf field: ruthless.v1.ConfigPublic.Registration registration = 3
     */
    registration?: ConfigPublic_Registration;
    /**
     * @generated from protobuf field: bool is_development = 4
     */
    isDevelopment: boolean;
    /**
     * @generated from protobuf field: ruthless.v1.ConfigPublic.AuthProvider auth_provider = 5
     */
    authProvider: ConfigPublic_AuthProvider;
}
/**
 * @generated from protobuf enum ruthless.v1.ConfigPublic.AuthProvider
 */
export enum ConfigPublic_AuthProvider {
    /**
     * @generated from protobuf enum value: AUTH_PROVIDER_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: AUTH_PROVIDER_GOOGLE = 1;
     */
    GOOGLE = 1,
    /**
     * @generated from protobuf enum value: AUTH_PROVIDER_FAKE = 2;
     */
    FAKE = 2
}
/**
 * @generated from protobuf message ruthless.v1.ConfigPublic.Limits
 */
export interface ConfigPublic_Limits {
    /**
     * @generated from protobuf field: uint32 max_user_name_length = 1
     */
    maxUserNameLength: number;
    /**
     * @generated from protobuf field: uint32 min_user_name_length = 2
     */
    minUserNameLength: number;
    /**
     * @generated from protobuf field: uint32 max_card_text_length = 3
     */
    maxCardTextLength: number;
    /**
     * @generated from protobuf field: uint32 max_deck_name_length = 4
     */
    maxDeckNameLength: number;
    /**
     * @generated from protobuf field: uint32 max_session_name_length = 5
     */
    maxSessionNameLength: number;
    /**
     * @generated from protobuf field: uint32 max_cards_per_user = 6
     */
    maxCardsPerUser: number;
    /**
     * @generated from protobuf field: uint32 max_decks_per_user = 7
     */
    maxDecksPerUser: number;
    /**
     * @generated from protobuf field: uint32 max_cards_per_deck = 8
     */
    maxCardsPerDeck: number;
    /**
     * @generated from protobuf field: uint32 max_contributors_per_deck = 9
     */
    maxContributorsPerDeck: number;
    /**
     * @generated from protobuf field: uint32 max_decks_per_session = 10
     */
    maxDecksPerSession: number;
    /**
     * @generated from protobuf field: uint32 max_players_per_session = 11
     */
    maxPlayersPerSession: number;
    /**
     * @generated from protobuf field: uint32 max_sessions_per_user = 12
     */
    maxSessionsPerUser: number;
    /**
     * @generated from protobuf field: uint32 max_cards_per_session = 13
     */
    maxCardsPerSession: number;
}
/**
 * @generated from protobuf message ruthless.v1.ConfigPublic.Game
 */
export interface ConfigPublic_Game {
    /**
     * @generated from protobuf field: uint32 min_required_players = 1
     */
    minRequiredPlayers: number;
}
/**
 * @generated from protobuf message ruthless.v1.ConfigPublic.Registration
 */
export interface ConfigPublic_Registration {
    /**
     * @generated from protobuf field: uint32 max_unique_identifier_recreations = 1
     */
    maxUniqueIdentifierRecreations: number;
    /**
     * @generated from protobuf field: string google_client_id = 2
     */
    googleClientId: string;
}
/**
 * @generated from protobuf message ruthless.v1.ConfigPrivate
 */
export interface ConfigPrivate {
    /**
     * @generated from protobuf field: ruthless.v1.ConfigPrivate.Registration registration = 1
     */
    registration?: ConfigPrivate_Registration;
}
/**
 * @generated from protobuf message ruthless.v1.ConfigPrivate.Registration
 */
export interface ConfigPrivate_Registration {
    /**
     * @generated from protobuf field: string google_client_secret = 1
     */
    googleClientSecret: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Config$Type extends MessageType<Config> {
    constructor() {
        super("ruthless.v1.Config", [
            { no: 1, name: "public", kind: "message", T: () => ConfigPublic },
            { no: 2, name: "private", kind: "message", T: () => ConfigPrivate }
        ]);
    }
    create(value?: PartialMessage<Config>): Config {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Config>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Config): Config {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ruthless.v1.ConfigPublic public */ 1:
                    message.public = ConfigPublic.internalBinaryRead(reader, reader.uint32(), options, message.public);
                    break;
                case /* ruthless.v1.ConfigPrivate private */ 2:
                    message.private = ConfigPrivate.internalBinaryRead(reader, reader.uint32(), options, message.private);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Config, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ruthless.v1.ConfigPublic public = 1; */
        if (message.public)
            ConfigPublic.internalBinaryWrite(message.public, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* ruthless.v1.ConfigPrivate private = 2; */
        if (message.private)
            ConfigPrivate.internalBinaryWrite(message.private, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ruthless.v1.Config
 */
export const Config = new Config$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfigPublic$Type extends MessageType<ConfigPublic> {
    constructor() {
        super("ruthless.v1.ConfigPublic", [
            { no: 1, name: "limits", kind: "message", T: () => ConfigPublic_Limits },
            { no: 2, name: "game", kind: "message", T: () => ConfigPublic_Game },
            { no: 3, name: "registration", kind: "message", T: () => ConfigPublic_Registration },
            { no: 4, name: "is_development", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "auth_provider", kind: "enum", T: () => ["ruthless.v1.ConfigPublic.AuthProvider", ConfigPublic_AuthProvider, "AUTH_PROVIDER_"] }
        ]);
    }
    create(value?: PartialMessage<ConfigPublic>): ConfigPublic {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isDevelopment = false;
        message.authProvider = 0;
        if (value !== undefined)
            reflectionMergePartial<ConfigPublic>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfigPublic): ConfigPublic {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ruthless.v1.ConfigPublic.Limits limits */ 1:
                    message.limits = ConfigPublic_Limits.internalBinaryRead(reader, reader.uint32(), options, message.limits);
                    break;
                case /* ruthless.v1.ConfigPublic.Game game */ 2:
                    message.game = ConfigPublic_Game.internalBinaryRead(reader, reader.uint32(), options, message.game);
                    break;
                case /* ruthless.v1.ConfigPublic.Registration registration */ 3:
                    message.registration = ConfigPublic_Registration.internalBinaryRead(reader, reader.uint32(), options, message.registration);
                    break;
                case /* bool is_development */ 4:
                    message.isDevelopment = reader.bool();
                    break;
                case /* ruthless.v1.ConfigPublic.AuthProvider auth_provider */ 5:
                    message.authProvider = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfigPublic, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ruthless.v1.ConfigPublic.Limits limits = 1; */
        if (message.limits)
            ConfigPublic_Limits.internalBinaryWrite(message.limits, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* ruthless.v1.ConfigPublic.Game game = 2; */
        if (message.game)
            ConfigPublic_Game.internalBinaryWrite(message.game, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* ruthless.v1.ConfigPublic.Registration registration = 3; */
        if (message.registration)
            ConfigPublic_Registration.internalBinaryWrite(message.registration, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bool is_development = 4; */
        if (message.isDevelopment !== false)
            writer.tag(4, WireType.Varint).bool(message.isDevelopment);
        /* ruthless.v1.ConfigPublic.AuthProvider auth_provider = 5; */
        if (message.authProvider !== 0)
            writer.tag(5, WireType.Varint).int32(message.authProvider);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ruthless.v1.ConfigPublic
 */
export const ConfigPublic = new ConfigPublic$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfigPublic_Limits$Type extends MessageType<ConfigPublic_Limits> {
    constructor() {
        super("ruthless.v1.ConfigPublic.Limits", [
            { no: 1, name: "max_user_name_length", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "min_user_name_length", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "max_card_text_length", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "max_deck_name_length", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "max_session_name_length", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "max_cards_per_user", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "max_decks_per_user", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 8, name: "max_cards_per_deck", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 9, name: "max_contributors_per_deck", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "max_decks_per_session", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 11, name: "max_players_per_session", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 12, name: "max_sessions_per_user", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 13, name: "max_cards_per_session", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ConfigPublic_Limits>): ConfigPublic_Limits {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.maxUserNameLength = 0;
        message.minUserNameLength = 0;
        message.maxCardTextLength = 0;
        message.maxDeckNameLength = 0;
        message.maxSessionNameLength = 0;
        message.maxCardsPerUser = 0;
        message.maxDecksPerUser = 0;
        message.maxCardsPerDeck = 0;
        message.maxContributorsPerDeck = 0;
        message.maxDecksPerSession = 0;
        message.maxPlayersPerSession = 0;
        message.maxSessionsPerUser = 0;
        message.maxCardsPerSession = 0;
        if (value !== undefined)
            reflectionMergePartial<ConfigPublic_Limits>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfigPublic_Limits): ConfigPublic_Limits {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 max_user_name_length */ 1:
                    message.maxUserNameLength = reader.uint32();
                    break;
                case /* uint32 min_user_name_length */ 2:
                    message.minUserNameLength = reader.uint32();
                    break;
                case /* uint32 max_card_text_length */ 3:
                    message.maxCardTextLength = reader.uint32();
                    break;
                case /* uint32 max_deck_name_length */ 4:
                    message.maxDeckNameLength = reader.uint32();
                    break;
                case /* uint32 max_session_name_length */ 5:
                    message.maxSessionNameLength = reader.uint32();
                    break;
                case /* uint32 max_cards_per_user */ 6:
                    message.maxCardsPerUser = reader.uint32();
                    break;
                case /* uint32 max_decks_per_user */ 7:
                    message.maxDecksPerUser = reader.uint32();
                    break;
                case /* uint32 max_cards_per_deck */ 8:
                    message.maxCardsPerDeck = reader.uint32();
                    break;
                case /* uint32 max_contributors_per_deck */ 9:
                    message.maxContributorsPerDeck = reader.uint32();
                    break;
                case /* uint32 max_decks_per_session */ 10:
                    message.maxDecksPerSession = reader.uint32();
                    break;
                case /* uint32 max_players_per_session */ 11:
                    message.maxPlayersPerSession = reader.uint32();
                    break;
                case /* uint32 max_sessions_per_user */ 12:
                    message.maxSessionsPerUser = reader.uint32();
                    break;
                case /* uint32 max_cards_per_session */ 13:
                    message.maxCardsPerSession = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfigPublic_Limits, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 max_user_name_length = 1; */
        if (message.maxUserNameLength !== 0)
            writer.tag(1, WireType.Varint).uint32(message.maxUserNameLength);
        /* uint32 min_user_name_length = 2; */
        if (message.minUserNameLength !== 0)
            writer.tag(2, WireType.Varint).uint32(message.minUserNameLength);
        /* uint32 max_card_text_length = 3; */
        if (message.maxCardTextLength !== 0)
            writer.tag(3, WireType.Varint).uint32(message.maxCardTextLength);
        /* uint32 max_deck_name_length = 4; */
        if (message.maxDeckNameLength !== 0)
            writer.tag(4, WireType.Varint).uint32(message.maxDeckNameLength);
        /* uint32 max_session_name_length = 5; */
        if (message.maxSessionNameLength !== 0)
            writer.tag(5, WireType.Varint).uint32(message.maxSessionNameLength);
        /* uint32 max_cards_per_user = 6; */
        if (message.maxCardsPerUser !== 0)
            writer.tag(6, WireType.Varint).uint32(message.maxCardsPerUser);
        /* uint32 max_decks_per_user = 7; */
        if (message.maxDecksPerUser !== 0)
            writer.tag(7, WireType.Varint).uint32(message.maxDecksPerUser);
        /* uint32 max_cards_per_deck = 8; */
        if (message.maxCardsPerDeck !== 0)
            writer.tag(8, WireType.Varint).uint32(message.maxCardsPerDeck);
        /* uint32 max_contributors_per_deck = 9; */
        if (message.maxContributorsPerDeck !== 0)
            writer.tag(9, WireType.Varint).uint32(message.maxContributorsPerDeck);
        /* uint32 max_decks_per_session = 10; */
        if (message.maxDecksPerSession !== 0)
            writer.tag(10, WireType.Varint).uint32(message.maxDecksPerSession);
        /* uint32 max_players_per_session = 11; */
        if (message.maxPlayersPerSession !== 0)
            writer.tag(11, WireType.Varint).uint32(message.maxPlayersPerSession);
        /* uint32 max_sessions_per_user = 12; */
        if (message.maxSessionsPerUser !== 0)
            writer.tag(12, WireType.Varint).uint32(message.maxSessionsPerUser);
        /* uint32 max_cards_per_session = 13; */
        if (message.maxCardsPerSession !== 0)
            writer.tag(13, WireType.Varint).uint32(message.maxCardsPerSession);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ruthless.v1.ConfigPublic.Limits
 */
export const ConfigPublic_Limits = new ConfigPublic_Limits$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfigPublic_Game$Type extends MessageType<ConfigPublic_Game> {
    constructor() {
        super("ruthless.v1.ConfigPublic.Game", [
            { no: 1, name: "min_required_players", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ConfigPublic_Game>): ConfigPublic_Game {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.minRequiredPlayers = 0;
        if (value !== undefined)
            reflectionMergePartial<ConfigPublic_Game>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfigPublic_Game): ConfigPublic_Game {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 min_required_players */ 1:
                    message.minRequiredPlayers = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfigPublic_Game, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 min_required_players = 1; */
        if (message.minRequiredPlayers !== 0)
            writer.tag(1, WireType.Varint).uint32(message.minRequiredPlayers);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ruthless.v1.ConfigPublic.Game
 */
export const ConfigPublic_Game = new ConfigPublic_Game$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfigPublic_Registration$Type extends MessageType<ConfigPublic_Registration> {
    constructor() {
        super("ruthless.v1.ConfigPublic.Registration", [
            { no: 1, name: "max_unique_identifier_recreations", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "google_client_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ConfigPublic_Registration>): ConfigPublic_Registration {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.maxUniqueIdentifierRecreations = 0;
        message.googleClientId = "";
        if (value !== undefined)
            reflectionMergePartial<ConfigPublic_Registration>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfigPublic_Registration): ConfigPublic_Registration {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 max_unique_identifier_recreations */ 1:
                    message.maxUniqueIdentifierRecreations = reader.uint32();
                    break;
                case /* string google_client_id */ 2:
                    message.googleClientId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfigPublic_Registration, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 max_unique_identifier_recreations = 1; */
        if (message.maxUniqueIdentifierRecreations !== 0)
            writer.tag(1, WireType.Varint).uint32(message.maxUniqueIdentifierRecreations);
        /* string google_client_id = 2; */
        if (message.googleClientId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.googleClientId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ruthless.v1.ConfigPublic.Registration
 */
export const ConfigPublic_Registration = new ConfigPublic_Registration$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfigPrivate$Type extends MessageType<ConfigPrivate> {
    constructor() {
        super("ruthless.v1.ConfigPrivate", [
            { no: 1, name: "registration", kind: "message", T: () => ConfigPrivate_Registration }
        ]);
    }
    create(value?: PartialMessage<ConfigPrivate>): ConfigPrivate {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ConfigPrivate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfigPrivate): ConfigPrivate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ruthless.v1.ConfigPrivate.Registration registration */ 1:
                    message.registration = ConfigPrivate_Registration.internalBinaryRead(reader, reader.uint32(), options, message.registration);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfigPrivate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ruthless.v1.ConfigPrivate.Registration registration = 1; */
        if (message.registration)
            ConfigPrivate_Registration.internalBinaryWrite(message.registration, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ruthless.v1.ConfigPrivate
 */
export const ConfigPrivate = new ConfigPrivate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfigPrivate_Registration$Type extends MessageType<ConfigPrivate_Registration> {
    constructor() {
        super("ruthless.v1.ConfigPrivate.Registration", [
            { no: 1, name: "google_client_secret", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ConfigPrivate_Registration>): ConfigPrivate_Registration {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.googleClientSecret = "";
        if (value !== undefined)
            reflectionMergePartial<ConfigPrivate_Registration>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConfigPrivate_Registration): ConfigPrivate_Registration {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string google_client_secret */ 1:
                    message.googleClientSecret = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConfigPrivate_Registration, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string google_client_secret = 1; */
        if (message.googleClientSecret !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.googleClientSecret);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ruthless.v1.ConfigPrivate.Registration
 */
export const ConfigPrivate_Registration = new ConfigPrivate_Registration$Type();
