// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "ruthless.proto" (package "ruthless.v1", syntax proto3)
// tslint:disable
import { GameService } from "./ruthless";
import type { GetGameBySessionRequest } from "./ruthless";
import type { GetHandResponse } from "./ruthless";
import type { GetHandRequest } from "./ruthless";
import type { SelectWinnerResponse } from "./ruthless";
import type { SelectWinnerRequest } from "./ruthless";
import type { PlayCardsResponse } from "./ruthless";
import type { PlayCardsRequest } from "./ruthless";
import type { StartGameRequest } from "./ruthless";
import type { GetGameRequest } from "./ruthless";
import type { Game } from "./ruthless";
import type { CreateGameRequest } from "./ruthless";
import { UserService } from "./ruthless";
import type { GetMeRequest } from "./ruthless";
import type { User } from "./ruthless";
import type { RegisterRequest } from "./ruthless";
import { SessionService } from "./ruthless";
import type { ListSessionsResponse } from "./ruthless";
import type { ListSessionsRequest } from "./ruthless";
import type { AddDeckToSessionResponse } from "./ruthless";
import type { AddDeckToSessionRequest } from "./ruthless";
import type { GetSessionRequest } from "./ruthless";
import type { JoinSessionRequest } from "./ruthless";
import type { Session } from "./ruthless";
import type { CreateSessionRequest } from "./ruthless";
import { DeckService } from "./ruthless";
import type { RemoveCardFromDeckResponse } from "./ruthless";
import type { RemoveCardFromDeckRequest } from "./ruthless";
import type { AddCardToDeckResponse } from "./ruthless";
import type { AddCardToDeckRequest } from "./ruthless";
import type { RemoveContributorResponse } from "./ruthless";
import type { RemoveContributorRequest } from "./ruthless";
import type { AddContributorResponse } from "./ruthless";
import type { AddContributorRequest } from "./ruthless";
import type { CreateDeckRequest } from "./ruthless";
import type { Deck } from "./ruthless";
import type { GetDeckRequest } from "./ruthless";
import type { ListDecksResponse } from "./ruthless";
import type { ListDecksRequest } from "./ruthless";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CardService } from "./ruthless";
import type { Empty } from "./google/protobuf/empty";
import type { DeleteCardRequest } from "./ruthless";
import type { Card } from "./ruthless";
import type { CreateCardRequest } from "./ruthless";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListCardsResponse } from "./ruthless";
import type { ListCardsRequest } from "./ruthless";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service ruthless.v1.CardService
 */
export interface ICardServiceClient {
    /**
     * @generated from protobuf rpc: ListCards
     */
    listCards(input: ListCardsRequest, options?: RpcOptions): UnaryCall<ListCardsRequest, ListCardsResponse>;
    /**
     * @generated from protobuf rpc: CreateCard
     */
    createCard(input: CreateCardRequest, options?: RpcOptions): UnaryCall<CreateCardRequest, Card>;
    /**
     * @generated from protobuf rpc: DeleteCard
     */
    deleteCard(input: DeleteCardRequest, options?: RpcOptions): UnaryCall<DeleteCardRequest, Empty>;
}
/**
 * @generated from protobuf service ruthless.v1.CardService
 */
export class CardServiceClient implements ICardServiceClient, ServiceInfo {
    typeName = CardService.typeName;
    methods = CardService.methods;
    options = CardService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListCards
     */
    listCards(input: ListCardsRequest, options?: RpcOptions): UnaryCall<ListCardsRequest, ListCardsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCardsRequest, ListCardsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateCard
     */
    createCard(input: CreateCardRequest, options?: RpcOptions): UnaryCall<CreateCardRequest, Card> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateCardRequest, Card>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteCard
     */
    deleteCard(input: DeleteCardRequest, options?: RpcOptions): UnaryCall<DeleteCardRequest, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteCardRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service ruthless.v1.DeckService
 */
export interface IDeckServiceClient {
    /**
     * @generated from protobuf rpc: ListDecks
     */
    listDecks(input: ListDecksRequest, options?: RpcOptions): UnaryCall<ListDecksRequest, ListDecksResponse>;
    /**
     * @generated from protobuf rpc: GetDeck
     */
    getDeck(input: GetDeckRequest, options?: RpcOptions): UnaryCall<GetDeckRequest, Deck>;
    /**
     * @generated from protobuf rpc: CreateDeck
     */
    createDeck(input: CreateDeckRequest, options?: RpcOptions): UnaryCall<CreateDeckRequest, Deck>;
    /**
     * @generated from protobuf rpc: AddContributor
     */
    addContributor(input: AddContributorRequest, options?: RpcOptions): UnaryCall<AddContributorRequest, AddContributorResponse>;
    /**
     * @generated from protobuf rpc: RemoveContributor
     */
    removeContributor(input: RemoveContributorRequest, options?: RpcOptions): UnaryCall<RemoveContributorRequest, RemoveContributorResponse>;
    /**
     * @generated from protobuf rpc: AddCardToDeck
     */
    addCardToDeck(input: AddCardToDeckRequest, options?: RpcOptions): UnaryCall<AddCardToDeckRequest, AddCardToDeckResponse>;
    /**
     * @generated from protobuf rpc: RemoveCardFromDeck
     */
    removeCardFromDeck(input: RemoveCardFromDeckRequest, options?: RpcOptions): UnaryCall<RemoveCardFromDeckRequest, RemoveCardFromDeckResponse>;
}
/**
 * @generated from protobuf service ruthless.v1.DeckService
 */
export class DeckServiceClient implements IDeckServiceClient, ServiceInfo {
    typeName = DeckService.typeName;
    methods = DeckService.methods;
    options = DeckService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListDecks
     */
    listDecks(input: ListDecksRequest, options?: RpcOptions): UnaryCall<ListDecksRequest, ListDecksResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDecksRequest, ListDecksResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDeck
     */
    getDeck(input: GetDeckRequest, options?: RpcOptions): UnaryCall<GetDeckRequest, Deck> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDeckRequest, Deck>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateDeck
     */
    createDeck(input: CreateDeckRequest, options?: RpcOptions): UnaryCall<CreateDeckRequest, Deck> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateDeckRequest, Deck>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddContributor
     */
    addContributor(input: AddContributorRequest, options?: RpcOptions): UnaryCall<AddContributorRequest, AddContributorResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddContributorRequest, AddContributorResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveContributor
     */
    removeContributor(input: RemoveContributorRequest, options?: RpcOptions): UnaryCall<RemoveContributorRequest, RemoveContributorResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveContributorRequest, RemoveContributorResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddCardToDeck
     */
    addCardToDeck(input: AddCardToDeckRequest, options?: RpcOptions): UnaryCall<AddCardToDeckRequest, AddCardToDeckResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddCardToDeckRequest, AddCardToDeckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveCardFromDeck
     */
    removeCardFromDeck(input: RemoveCardFromDeckRequest, options?: RpcOptions): UnaryCall<RemoveCardFromDeckRequest, RemoveCardFromDeckResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveCardFromDeckRequest, RemoveCardFromDeckResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service ruthless.v1.SessionService
 */
export interface ISessionServiceClient {
    /**
     * @generated from protobuf rpc: CreateSession
     */
    createSession(input: CreateSessionRequest, options?: RpcOptions): UnaryCall<CreateSessionRequest, Session>;
    /**
     * @generated from protobuf rpc: JoinSession
     */
    joinSession(input: JoinSessionRequest, options?: RpcOptions): UnaryCall<JoinSessionRequest, Session>;
    /**
     * @generated from protobuf rpc: GetSession
     */
    getSession(input: GetSessionRequest, options?: RpcOptions): UnaryCall<GetSessionRequest, Session>;
    /**
     * @generated from protobuf rpc: AddDeckToSession
     */
    addDeckToSession(input: AddDeckToSessionRequest, options?: RpcOptions): UnaryCall<AddDeckToSessionRequest, AddDeckToSessionResponse>;
    /**
     * @generated from protobuf rpc: ListSessions
     */
    listSessions(input: ListSessionsRequest, options?: RpcOptions): UnaryCall<ListSessionsRequest, ListSessionsResponse>;
}
/**
 * @generated from protobuf service ruthless.v1.SessionService
 */
export class SessionServiceClient implements ISessionServiceClient, ServiceInfo {
    typeName = SessionService.typeName;
    methods = SessionService.methods;
    options = SessionService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateSession
     */
    createSession(input: CreateSessionRequest, options?: RpcOptions): UnaryCall<CreateSessionRequest, Session> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateSessionRequest, Session>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: JoinSession
     */
    joinSession(input: JoinSessionRequest, options?: RpcOptions): UnaryCall<JoinSessionRequest, Session> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<JoinSessionRequest, Session>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSession
     */
    getSession(input: GetSessionRequest, options?: RpcOptions): UnaryCall<GetSessionRequest, Session> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSessionRequest, Session>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddDeckToSession
     */
    addDeckToSession(input: AddDeckToSessionRequest, options?: RpcOptions): UnaryCall<AddDeckToSessionRequest, AddDeckToSessionResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddDeckToSessionRequest, AddDeckToSessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListSessions
     */
    listSessions(input: ListSessionsRequest, options?: RpcOptions): UnaryCall<ListSessionsRequest, ListSessionsResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSessionsRequest, ListSessionsResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service ruthless.v1.UserService
 */
export interface IUserServiceClient {
    /**
     * @generated from protobuf rpc: Register
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, User>;
    /**
     * @generated from protobuf rpc: GetMe
     */
    getMe(input: GetMeRequest, options?: RpcOptions): UnaryCall<GetMeRequest, User>;
}
/**
 * @generated from protobuf service ruthless.v1.UserService
 */
export class UserServiceClient implements IUserServiceClient, ServiceInfo {
    typeName = UserService.typeName;
    methods = UserService.methods;
    options = UserService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Register
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, User> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRequest, User>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMe
     */
    getMe(input: GetMeRequest, options?: RpcOptions): UnaryCall<GetMeRequest, User> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMeRequest, User>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service ruthless.v1.GameService
 */
export interface IGameServiceClient {
    /**
     * @generated from protobuf rpc: CreateGame
     */
    createGame(input: CreateGameRequest, options?: RpcOptions): UnaryCall<CreateGameRequest, Game>;
    /**
     * @generated from protobuf rpc: GetGame
     */
    getGame(input: GetGameRequest, options?: RpcOptions): UnaryCall<GetGameRequest, Game>;
    /**
     * @generated from protobuf rpc: StartGame
     */
    startGame(input: StartGameRequest, options?: RpcOptions): UnaryCall<StartGameRequest, Game>;
    /**
     * @generated from protobuf rpc: PlayCards
     */
    playCards(input: PlayCardsRequest, options?: RpcOptions): UnaryCall<PlayCardsRequest, PlayCardsResponse>;
    /**
     * @generated from protobuf rpc: SelectWinner
     */
    selectWinner(input: SelectWinnerRequest, options?: RpcOptions): UnaryCall<SelectWinnerRequest, SelectWinnerResponse>;
    /**
     * @generated from protobuf rpc: GetHand
     */
    getHand(input: GetHandRequest, options?: RpcOptions): UnaryCall<GetHandRequest, GetHandResponse>;
    /**
     * @generated from protobuf rpc: GetGameBySession
     */
    getGameBySession(input: GetGameBySessionRequest, options?: RpcOptions): UnaryCall<GetGameBySessionRequest, Game>;
}
/**
 * @generated from protobuf service ruthless.v1.GameService
 */
export class GameServiceClient implements IGameServiceClient, ServiceInfo {
    typeName = GameService.typeName;
    methods = GameService.methods;
    options = GameService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateGame
     */
    createGame(input: CreateGameRequest, options?: RpcOptions): UnaryCall<CreateGameRequest, Game> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateGameRequest, Game>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetGame
     */
    getGame(input: GetGameRequest, options?: RpcOptions): UnaryCall<GetGameRequest, Game> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetGameRequest, Game>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StartGame
     */
    startGame(input: StartGameRequest, options?: RpcOptions): UnaryCall<StartGameRequest, Game> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<StartGameRequest, Game>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PlayCards
     */
    playCards(input: PlayCardsRequest, options?: RpcOptions): UnaryCall<PlayCardsRequest, PlayCardsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<PlayCardsRequest, PlayCardsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SelectWinner
     */
    selectWinner(input: SelectWinnerRequest, options?: RpcOptions): UnaryCall<SelectWinnerRequest, SelectWinnerResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<SelectWinnerRequest, SelectWinnerResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetHand
     */
    getHand(input: GetHandRequest, options?: RpcOptions): UnaryCall<GetHandRequest, GetHandResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetHandRequest, GetHandResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetGameBySession
     */
    getGameBySession(input: GetGameBySessionRequest, options?: RpcOptions): UnaryCall<GetGameBySessionRequest, Game> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetGameBySessionRequest, Game>("unary", this._transport, method, opt, input);
    }
}
